### ISSUE TITLE
how can i find my mysql root password?

### ISSUE THREAD

**Issue by ID404** [QuantumObject/docker-cacti#13]
docker-cacti run fine ,but I have problem with installing the plugin.After installing the thold,it told "You are running MySQL in Strict Mode, which is not supported by Thold." ,I want to login to mysql ,but I dont know mysql root password, where can find it?

**Comment by angelrr7702** [comment]
Hi,
   at pre-conf.sh scrip you can find the password ,,, 

 mysqladmin -u root password mysqlpsswd
 mysqladmin -u root -pmysqlpsswd reload
 mysqladmin -u root -pmysqlpsswd create cacti
 mysql -u root -pmysqlpsswd cacti < /usr/share/cacti/conf_templates/cacti.sql


sincerely
Angel Rodriguez
