### ISSUE TITLE
Volumes for peristent data?

### ISSUE THREAD

**Issue by SlothCroissant** [QuantumObject/docker-cacti#17]
Love the container! Looking for one "feature" to be added - persistent volume mappings so one could destroy the container and have everything persist after a re-create. 

For example, with many containers, all config/db files are kept in a folder which is kept as a persistent data volume (`-v` flag in docker run) so that everything is in place in case of any destruction of the container itself. Once you re-create, your config/db/etc are already in place and the container continues like it never left off. 

Would this be possible with this container? Can it be done now with some creative volume mappings? I'm not sure where Cacti keeps all of its relevant data. 

Thanks!

**Comment by Jujonet** [comment]
+1

**Comment by SoulGit** [comment]
+1

**Comment by florid2** [comment]
+1

**Comment by Vitiate** [comment]
Ok, I made this work with the following compose file:
version: "3"
services:
  cacti:
    image: quantumobject/docker-cacti
    restart: always
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
      - "163:163"
    environment:
      - TZ=America/Edmonton
    volumes:
      - /opt/cacti/plugins/:/opt/cacti/plugins/
      - /opt/cacti/logs:/var/log/
      - /opt/cacti/templates:/opt/cacti/templates/
      - /opt/cacti/mysql:/var/lib/mysql

So, this will get you started, after the container is up you need to get into it with an interactive shell: docker exec -it cacti_cacti_1 /bin/bash
edit the /etc/mysql/my.cnf and comment out the time zone line
run: mysql_install_db inside the container
from outside the container do a chown -R uid:pid /opt/cacti/mysql  (use the uid/pid from the container, in mycase it was 101:102, you can even add this user/group to your host machine if you wish).

Now you should have a running mysql daemon, perform the following in the container:

 mysqladmin -u root password mysqlpsswd
 mysqladmin -u root -pmysqlpsswd reload
 mysqladmin -u root -pmysqlpsswd create cacti
 echo "GRANT ALL ON cacti.* TO cacti@localhost IDENTIFIED BY '9PIu8AbWQSf8'; flush privileges; " | mysql -u root -pmysqlpsswd 
 echo "GRANT SELECT ON mysql.time_zone_name TO cacti@localhost IDENTIFIED BY '9PIu8AbWQSf8'; flush privileges; " | mysql -u root -pmysqlpsswd 
 
 mysql -u root -pmysqlpsswd cacti < /opt/cacti/cacti.sql
 mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -pmysqlpsswd mysql

You can now go back into /etc/mysql/my.cnf and change the timezone back if you care, I do not believe it matters but I dunno.

You should now have a persistent database and be good to go. 

It would be nice if the creator moved the configuration of the database out of the pre and into a first boot or something, would resolve this issue.

**Comment by Zunipox** [comment]
I tried this, everything worked fine until:

# mysqladmin -u root password mysqlpsswd

mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or directory")'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!

The database files gets created in the volume (/opt/cacti/mysql:/var/lib/mysql)

Is it due to permissions?
I started the container as PUID 1000 (myuser), PGID 100 (users)
chown -R myuser:users /opt/cacti/mysql

**Comment by islander** [comment]
Hello, in [my fork](https://github.com/islander/docker-cacti) I've reinplemented MySQL initialization with environment variables (so, there you can use separate data container or any existing MySQL server).

If you interested, I can make a pull request.

**Comment by stuntguy3000** [comment]
@islander How do you setup your fork? I don't understand how to setup the DB.

**Comment by lux4rd0** [comment]
Looking for the same - thought I could just overlay a persistent mysql DB volume before I looked at the build. :) Love this Cacti Docker build but without persistent data volumes - it's a no go for me. I push containers around in K8S all the time and I need to be able to keep the data I care about outside of the container... Thanks! Will keep an eye on this...

**Comment by islander** [comment]
@stuntguy3000 through environment variables, see example `docker-compose.yml`, you need to pass mysql root password, and cacti mysql user/password:

```
services:
  cactiweb:
    image: kiba/docker-cacti:latest
    depends_on:
      - cactidb
    environment:
      - MYSQL_ENV_HOST=cactidb
      - MYSQL_ENV_DBNAME=cacti
      - MYSQL_ENV_USER=cacti
      - MYSQL_ENV_USER_PASSWD=cactiuserpasswd
      - MYSQL_ENV_ROOT_PASSWD=cactipasswd
  cactidb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=cactipasswd
```

If you already have MySQL server, just pass `MYSQL_ENV_*` variables to the container: `docker run -e MYSQL_ENV_HOST=db.example.com -e MYSQL_ENV_USER=cacti -e MYSQL_ENV_USER_PASSWD=cactiuserpasswd -e MYSQL_ENV_ROOT_PASSWD=cactipasswd kiba/docker-cacti`, etc.

You need mysql root access for database initialization (for creating cacti schema).

**Comment by angelrr7702** [comment]
Update to version 1.2.8
add libtool needed for cacti-spine that was missing ..
update some database configuration.
add some Volumes to add persistence in the future . (still no bulletproof)

**Comment by maja68** [comment]
Thanks for adding some volumes.
Do you see a chance to add /opt/cacti/rrd as persisted volume? This would be useful to avoid copying the rrd files into the container.

**Comment by angelrr7702** [comment]
done, wait for docker hub to recompile it.
