### ISSUE TITLE
mysqld_safe Logging to '/var/lib/mysql/6c96fbab63bf.err'

### ISSUE THREAD

**Issue by Cyriltra** [QuantumObject/docker-cacti#19]
Hello,

after the fix of previous issue, I got error with the db:

`cacti         | 2017-11-19T11:16:34.960314349Z Starting pre-service scritps in /etc/my_init.d
cacti         | 2017-11-19T11:16:34.960743497Z *** Running: /etc/my_init.d/startup.sh
cacti         | 2017-11-19T11:16:35.018472827Z /sbin/my_init: line 22: export: `affinity:container': not a valid identifier
cacti         | 2017-11-19T11:16:35.031249929Z starting rc.local scritps
cacti         | 2017-11-19T11:16:35.031311721Z *** Running: /etc/rc.local
cacti         | 2017-11-19T11:16:35.042693762Z /sbin/my_init: line 22: export: `affinity:container': not a valid identifier
cacti         | 2017-11-19T11:16:35.055606135Z Booting runit daemon...
cacti         | 2017-11-19T11:16:35.055622745Z Process runsvdir running with PID 202
cacti         | 2017-11-19T11:16:35.061223824Z ok: run: mysqld: (pid 211) 0s
cacti         | 2017-11-19T11:16:35.102416731Z 171119 11:16:35 mysqld_safe Logging to '/var/lib/mysql/6c96fbab63bf.err'.
cacti         | 2017-11-19T11:16:35.128673758Z 171119 11:16:35 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
cacti         | 2017-11-19T11:16:35.180584057Z Created directory: /var/lib/snmp/mib_indexes
cacti         | 2017-11-19T11:16:35.254723471Z NET-SNMP version 5.7.3
cacti         | 2017-11-19T11:16:36.764681882Z 171119 11:16:36 mysqld_safe Logging to '/var/lib/mysql/6c96fbab63bf.err'.
cacti         | 2017-11-19T11:16:36.777198558Z 171119 11:16:36 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
cacti         | 2017-11-19T11:16:38.167093764Z 171119 11:16:38 mysqld_safe Logging to '/var/lib/mysql/6c96fbab63bf.err'.
cacti         | 2017-11-19T11:16:38.178813086Z 171119 11:16:38 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
cacti         | 2017-11-19T11:16:39.545312746Z 171119 11:16:39 mysqld_safe Logging to '/var/lib/mysql/6c96fbab63bf.err'.
cacti         | 2017-11-19T11:16:39.562889812Z 171119 11:16:39 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
cacti         | 2017-11-19T11:16:40.936182953Z 171119 11:16:40 mysqld_safe Logging to '/var/lib/mysql/6c96fbab63bf.err'.
cacti         | 2017-11-19T11:16:40.947719781Z 171119 11:16:40 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
cacti         | 2017-11-19T11:16:42.317236013Z 171119 11:16:42 mysqld_safe Logging to '/var/lib/mysql/6c96fbab63bf.err'.
cacti         | 2017-11-19T11:16:42.329659453Z 171119 11:16:42 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql`

Thank you

**Comment by angelrr7702** [comment]
update version 1.1.38 and to Ubuntu 18.04, no idea if this error still show...

**Comment by angelrr7702** [comment]
Update to version 1.2.8
add libtool needed for cacti-spine that was missing ..
update some database configuration.
add some Volumes to add persistence in the future . (still no bulletproof)
