### ISSUE TITLE
PHP timezone CLI vs Apache2

### ISSUE THREAD

**Issue by robisonjoel** [QuantumObject/docker-cacti#20]
I noticed an issue where the poller uses a different TZ than the web ui, this also means the RRD's get generated with the wrong timestamps.  
/etc/php/7.0/cli/php.ini needs to be updated the same way as /etc/php/7.0/apache2/php.ini

**Comment by robisonjoel** [comment]
#21

**Comment by angelrr7702** [comment]
Thanks for your help . pull done , and docker image building now.
