### ISSUE TITLE
Docker build fail with cacti 0.8.8h

### ISSUE THREAD

**Issue by jeffporrino** [QuantumObject/docker-cacti#22]
Hello everyone, i'm new at here so, i'm trying to rebuild your image but changing the cacti version from latest to 0.8.8h, however, everytime that i build up the image, it crashs after preconf.sh, this is the error:

**ERROR 1071 (42000) at line 1916: Specified key was too long; max key length is 1000 bytes
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.**

see my Dockerfile

#name of container: docker-cacti
#versison of container: 0.6.1
FROM quantumobject/docker-baseimage:16.04
MAINTAINER Angel Rodriguez  "angel@quantumobject.com"

ENV TZ America/New_York

# Update the container
#Installation of nesesary package/software for this containers...
 RUN apt-get update && echo $TZ > /etc/timezone && DEBIAN_FRONTEND=noninteractive apt-get install -yq mariadb-server mariadb-client php7.0 build-essential\
                                                            apache2  snmp libapache2-mod-php7.0 libssl-dev \
                                                            rrdtool librrds-perl php7.0-mysql\
                                                            php7.0-xml php7.0-ldap php7.0-mbstring \
                                                            php7.0-gd php7.0-snmp php7.0-gmp php7.0-mcrypt \
                                                            libmysqlclient-dev libsnmp-dev help2man git \
                                                            snmpd python-netsnmp libnet-snmp-perl snmp-mibs-downloader \
                    && cd /opt/ \
                    && wget https://www.cacti.net/downloads/cacti-0.8.8h.tar.gz \
                    && ver=$(tar -tf cacti-0.8.8h.tar.gz | head -n1 | tr -d /) \
                    && tar -xvf cacti-0.8.8h.tar.gz && mv $ver cacti \
                    && rm cacti-0.8.8h.tar.gz \
                    && apt-get clean \
                    && rm -rf /tmp/* /var/tmp/*  \
                    && rm -rf /var/lib/apt/lists/*

# Ensure cron is allowed to run
RUN sed -i 's/^\(session\s\+required\s\+pam_loginuid\.so.*$\)/# \1/g' /etc/pam.d/cron

##Get Mibs
RUN /usr/bin/download-mibs
RUN echo 'mibs +ALL' >> /etc/snmp/snmp.conf
## fix prblem with mibs downloader and ubuntu 16.04
RUN rm /usr/share/mibs/ietf/IPSEC-SPD-MIB \
    && rm /usr/share/mibs/ietf/IPATM-IPMC-MIB \
    && rm /usr/share/mibs/iana/IANA-IPPM-METRICS-REGISTRY-MIB \
    && rm /usr/share/mibs/ietf/SNMPv2-PDU

##startup scripts
#Pre-config scrip that maybe need to be run one time only when the container run the first time .. using a flag to don't
#run it again ... use for conf for service ... when run the first time ...
RUN mkdir -p /etc/my_init.d
COPY startup.sh /etc/my_init.d/startup.sh
RUN chmod +x /etc/my_init.d/startup.sh

##Adding Deamons to containers
# to add apache2 deamon to runit
RUN mkdir -p /etc/service/apache2  /var/log/apache2 ; sync
COPY apache2.sh /etc/service/apache2/run
RUN chmod +x /etc/service/apache2/run  \
    && cp /var/log/cron/config /var/log/apache2/ \
    && chown -R www-data /var/log/apache2

# to add mysqld deamon to runit
RUN mkdir -p /etc/service/mysqld /var/log/mysqld ; sync
COPY mysqld.sh /etc/service/mysqld/run
RUN chmod +x /etc/service/mysqld/run  \
    && cp /var/log/cron/config /var/log/mysqld/ \
    && chown -R mysql /var/log/mysqld

# to add mysqld deamon to runit
RUN mkdir -p /etc/service/snmpd /var/log/snmpd ; sync
COPY snmpd.sh /etc/service/snmpd/run
RUN chmod +x /etc/service/snmpd/run  \
   && cp /var/log/cron/config /var/log/snmpd/ \
   && chown -R snmp /var/log/snmpd

#add files and script that need to be use for this container
#include conf file relate to service/daemon
#additionsl tools to be use internally
COPY snmpd.conf /etc/snmp/snmpd.conf
COPY debian.conf /opt/cacti/include/config.php
COPY spine.conf /usr/local/spine/etc/spine.conf

#pre-config scritp for different service that need to be run when container image is create
#maybe include additional software that need to be installed ... with some service running ... like example mysqld
COPY pre-conf.sh /sbin/pre-conf
RUN chmod +x /sbin/pre-conf ; sync \
    && /bin/bash -c /sbin/pre-conf \
    && rm /sbin/pre-conf

##scritp that can be running from the outside using docker-bash tool ...
## for example to create backup for database with convitation of VOLUME   dockers-bash container_ID backup_mysql
COPY backup.sh /sbin/backup
COPY restore.sh /sbin/restore
RUN chmod +x /sbin/backup /sbin/restore
VOLUME /var/backups

# to allow access from outside of the container  to the container service
# at that ports need to allow access from firewall if need to access it outside of the server.
EXPOSE 80

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

and my pre-conf.sh

#!/bin/bash

cd /opt/cacti/plugins
# download the source
git clone -b master https://github.com/Cacti/plugin_thold.git
# rename it to thold, yes it matters...
mv plugin_thold thold

touch /opt/cacti/log/cacti.log
chown -R www-data:www-data /opt/cacti/

#Initial conf for mysql
mysql_install_db
#for configuriing database
/usr/bin/mysqld_safe &

 sleep 3s

 mysqladmin -u root password mysqlpsswd
 mysqladmin -u root -pmysqlpsswd reload
 mysqladmin -u root -pmysqlpsswd create cacti
 echo "GRANT ALL ON cacti.* TO cacti@localhost IDENTIFIED BY '9PIu8AbWQSf8'; flush privileges; " | mysql -u root -pmysqlpsswd
 echo "GRANT SELECT ON mysql.time_zone_name TO cacti@localhost IDENTIFIED BY '9PIu8AbWQSf8'; flush privileges; " | mysql -u root -pmysqlpsswd

 mysql -u root -pmysqlpsswd cacti < /opt/cacti/cacti.sql
 mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -pmysqlpsswd mysql

 #to fix error relate to ip address of container apache2
 echo "ServerName localhost" | tee /etc/apache2/conf-available/fqdn.conf
 ln -s /etc/apache2/conf-available/fqdn.conf /etc/apache2/conf-enabled/fqdn.conf

 # to create a link for the cacti web directory
 ln -s /opt/cacti/ /var/www/html/cacti

 #configure poller Crontab
 echo "*/5 * * * * www-data php /opt/cacti/poller.php > /dev/null 2>&1" >> /etc/crontab

killall mysqld
sleep 2s

mv /etc/mysql/my.cnf /etc/mysql/my.cnf-bkup
echo "
[mysqld]

max_heap_table_size = 1073741824
max_allowed_packet = 16777216
tmp_table_size = 134217728
join_buffer_size = 134217728
innodb_buffer_pool_size = 4294967296
innodb_doublewrite = OFF
innodb_flush_log_at_timeout = 10
innodb_read_io_threads = 32
innodb_write_io_threads = 16
collation-server = utf8mb4_unicode_ci
character-set-server = utf8mb4
" > /etc/mysql/my.cnf
systemctl restart mysql

cd /opt/
wget http://www.cacti.net/downloads/spine/cacti-spine-0.8.8h.tar.gz
ver=$(tar -tf cacti-spine-0.8.8h.tar.gz | head -n1 | tr -d /)
tar -xvf /opt/cacti-spine-0.8.8h.tar.gz
cd /opt/$ver/
./configure
make
make install

Anyone knows how can i fix this?

**Comment by angelrr7702** [comment]
right now only  have version Version 1.1.38 , dealing with to many container , unable to give time for older version .
