### ISSUE TITLE
poller not running from cron?

### ISSUE THREAD

**Issue by MrDibbley** [QuantumObject/docker-cacti#24]
poller runs manually but dosent seem to be running from cron every 5 minutes as expected

**Comment by tomeq82** [comment]
as of 6th of july - poller doesn't run from cron at all. Cron command launches perfectly alone, with no errors. Spine runs also fine, no errors. But cron job is not being started for some reason...

**Comment by angelrr7702** [comment]
fix /etc/crontab file ..   but need to check the path to Spine binary is /usr/local/spine/bin/spine in the configuration>>setting>>path at console cacti .

**Comment by tomeq82** [comment]
Path to spine is correct (triplechecked), also path in /etc/crontab is just fine. Copy pasted cron line launches the poller just fine from shell, but cron doesn't seem to work....

**Comment by angelrr7702** [comment]
before was * /5 * * * *  ... that was not right and change to 5  * * * * at crontab .
