### ISSUE TITLE
Graphing latency with ICMP

### ISSUE THREAD

**Issue by Elrainia** [QuantumObject/docker-cacti#25]
Hi,

I'm new to the world of Docker, but am a long time user of Cacti wishing to simplify our installation by using Docker.

As well as the usual SNMP monitoring, we've traditionally graphed latency to a number of hosts using a combination of TCP Ping and UDP Ping on various ports with no issues, however I can't get this to work for the life of me in this container.

I had a look around inside the container and the traditional ping.pl script is present and correct under cacti/scripts, but I can't find any ping binaries (/bin/, /usr/bin/, /sbin/ or /usr/sbin/). Is the problem simply that ping has not been included in the build or am I missing something a bit more subtle?

Thanks in advance for any thoughts and thanks for putting this container together, we're well impressed (ICMP monitoring aside :-) )

Malc

**Comment by dropthemic** [comment]
ping command is missing from the image. just install ping:

> apt-get update
> apt-get install iputils-ping

**Comment by angelrr7702** [comment]
iputils-ping was added done. .
