### ISSUE TITLE
Error opening specified endpoint "161"

### ISSUE THREAD

**Issue by tinuva** [QuantumObject/docker-cacti#29]
When using this container, my docker logs are spammed with the following:

cacti           | Error opening specified endpoint "161"
cacti           | Server Exiting with code 1

I believe this is because snmpd is launched as the user Debian-snmp and this user doesn't have permission to bind to port 161 (below 1024).

Now I see online there are many ways to resolve this, but I would like this resolved for this docker image.

**Comment by angelrr7702** [comment]
Temporal I change to root for snmpd , if you find link how to fix it please add to this issue .

**Comment by tinuva** [comment]
I think the difference is in how snmpd is launched in this container versus how debian/ubuntu launch it.

In container (without updating to the one where you use root), its launched with the options from /etc/service/snmpd/run : 
exec chpst -u Debian-snmp /usr/sbin/snmpd -f 2>&1

In debian, its launched different, I suspect it starts as root, and snmpd then change itself to the snmpd user:

/usr/sbin/snmpd -Lsd -Lf /dev/null -u Debian-snmp -g Debian-snmp -I -smux mteTrigger mteTriggerConf -f

So if you change /etc/service/snmpd/run to something along the lines of:
exec chpst -u root /usr/sbin/snmpd -u Debian-snmp -g Debian-snmp -f 2>&1

In fact I quickly tested that in my running container, and it immediately fixed the log spamming issue, as well as running snmpd as the user Debian-snmp

**Comment by angelrr7702** [comment]
Thanks , compiling it now with modification.
