### ISSUE TITLE
cmd.php or spine?

### ISSUE THREAD

**Issue by WirthmU** [QuantumObject/docker-cacti#33]
I keep getting the following error lines:

`2019/08/18 21:22:41 - CMDPHP PHP ERROR WARNING Backtrace: (/utilities.php[59]:utilities_view_logfile(), /utilities.php[1066]:strpos(), CactiErrorHandler())`

`2019/08/18 21:22:41 - ERROR PHP WARNING: strpos(): Empty needle in file: /opt/cacti/utilities.php on line: 1066`

I am running on cmd.php no spine installed. Is this the reason?

**Comment by WirthmU** [comment]
###

**Comment by WirthmU** [comment]
I got this from the cacti repository:

> Then I believe that the error you saw has already been resolved in a later version as I do recall correcting a needle problem.>

So could you please upgrade the docker to the latest version (1.2.5).

Thank you

**Comment by angelrr7702** [comment]
building at Docker Hub ..

**Comment by angelrr7702** [comment]
Done Building ,,please check if error gone

**Comment by WirthmU** [comment]
The error has been fixed by the update.
Great work btw!
