### ISSUE TITLE
wrong my.cnf

### ISSUE THREAD

**Issue by michaelscl** [QuantumObject/docker-cacti#36]
MySQL is not set up correctly.
You need to make adjustments manually.

Can you add this to Dockrefile?

Thanks

Michael
```
docker exec -it cacti /bin/sed -i 's!memory_limit = 128M!memory_limit = 512M!' /etc/php/7.2/apache2/php.ini
docker exec -it cacti /bin/sed -i 's!max_execution_time = 30!max_execution_time = 60!' /etc/php/7.2/apache2/php.ini
docker exec -it cacti /etc/init.d/apache2 reload

docker exec -it cacti /bin/bash
echo -e "join_buffer_size=256M\n" >> /etc/mysql/my.cnf
echo -e "innodb_file_format=Barracuda\n" >> /etc/mysql/my.cnf
echo -e "innodb_large_prefix=1\n" >> /etc/mysql/my.cnf
echo -e "innodb_buffer_pool_instances=33\n" >> /etc/mysql/my.cnf
echo -e "innodb_io_capacity=5000\n" >> /etc/mysql/my.cnf
echo -e "innodb_doublewrite=on\n" >> /etc/mysql/my.cnf
exit
docker exec -it cacti /etc/init.d/mysql restart

docker exec -it cacti /usr/bin/mysql cacti
ALTER DATABASE cacti CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
exit
```

**Comment by angelrr7702** [comment]
Normal is done at for this container at :
   pre-conf.sh 

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
done, please check again ..

**Comment by michaelscl** [comment]
Great, thank you!
![image](https://user-images.githubusercontent.com/31956130/68339093-2c0fd500-00e4-11ea-8c87-45eab97a6d6d.png)

**Comment by michaelscl** [comment]
but, the last one error:
![image](https://user-images.githubusercontent.com/31956130/68340250-595d8280-00e6-11ea-9603-6bf63650c0ed.png)

command:
`echo "ALTER DATABASE cacti CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" | /usr/bin/mysql cacti`

many thanks

**Comment by angelrr7702** [comment]
pull request accepted , I will build it now ..

**Comment by angelrr7702** [comment]
build done.

**Comment by michaelscl** [comment]
thanks
