### ISSUE TITLE
Unzip command is not included in your container

### ISSUE THREAD

**Issue by q2dg** [QuantumObject/docker-cacti#37]
Hello. 
I want to do instructions you show in README to install flowview plugin but when I want to unzip "developer.zip" file I can't because there's no unzip command available. 
I've tried to install but apt command doesn't find any external repository and I don't want to mess with network configuration 
Thanks!

**Comment by angelrr7702** [comment]
unzip added , need to wait for the build to be done at docker hub .

sincerely
Angel Rodriguez

**Comment by angelrr7702** [comment]
build done.
