### ISSUE TITLE
Problem with cacti 1.2.10 installing ....

### ISSUE THREAD

**Issue by angelrr7702** [QuantumObject/docker-cacti#42]
Please check this link

https://github.com/Cacti/cacti/issues/3313

**Comment by angelrr7702** [comment]
![image](https://user-images.githubusercontent.com/97704/77865167-f6869800-71fa-11ea-92bb-650bab74acee.png)

" Unchecking this one solve the installation problem"

**Comment by mckaygerhard** [comment]
but we cannot use the stats template!

**Comment by angelrr7702** [comment]
building 1.2.11 to check if cacti release fix it.

**Comment by angelrr7702** [comment]
yes, that fix it ...
