### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by vbarahona** [QuantumObject/docker-cacti#46]
Hi,

thanks for the project. It's really useful and save me a lot of time. 

One question. Is there any easy way to add ssl support to the apache service? I mean native support not through a reverse proxy out of the container.

Regards

**Comment by angelrr7702** [comment]
there are different way to add SSL support ,, I normally used another two container for it  .. 

note: deploy this container behind proxy with SSL for extra security:

https://github.com/jwilder/nginx-proxy

https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion
