### ISSUE TITLE
CRON unable to execute

### ISSUE THREAD

**Issue by tomislacker** [QuantumObject/docker-cacti#5]
Contents of `/var/log/auth.log`:

```
Jan  9 00:00:01 4d6a2ea17f53 CRON[28638]: pam_loginuid(cron:session): Error writing /proc/self/loginuid: Operation not permitted
Jan  9 00:00:01 4d6a2ea17f53 CRON[28638]: pam_loginuid(cron:session): set_loginuid failed
Jan  9 00:00:01 4d6a2ea17f53 CRON[28638]: pam_unix(cron:session): session opened for user www-data by (uid=0)
```

**Comment by angelrr7702** [comment]
I will check if I need to move this fix to my baseimage or keep it at this at cacti container only . I need to check if this problem appear on other containers.

**Comment by tomislacker** [comment]
There may also be a better way to resolve it too but given [man pam_loginuid(8)](http://linux.die.net/man/8/pam_loginuid), I don't think it's necessary to have for the vast majority of the containers' users.
