### ISSUE TITLE
Suggestion: Employ logrotate

### ISSUE THREAD

**Issue by tomislacker** [QuantumObject/docker-cacti#7]
### Observation
There's something wrong with the snmpd daemon inside the container, which should probably be filed as another issue, but that failure caused `/var/log/snmpd.log` to grow to ~923MB over the course of 4 days or so.

### Resolution
Establish log rotate policies for:
- `/var/log/*.log`
- `/var/log/cacti/*`
- *Others? I haven't explored everything quite yet.*

**Comment by angelrr7702** [comment]
thanks for info I will check ..

**Comment by CyrilPeponnet** [comment]
Same here, my container stopped working after the overlay as reached 10GB (this is the default when using docker under centos7 with device-mapper and loopdevices). My snmpd.log is 1.7GB after 7 days of runs (lot of errors not sure why). Otherwise it works fine :)

**Comment by angelrr7702** [comment]
I remove the redirection of the log  to snmpd.log at runit run script and I enable log to snmpd internally. I still need to fix configuration problem that is create at ubuntu baseimage and snmp when  installed with snmp-mibs-downloader (ubuntu don't configure it because of license ...)

**Comment by CyrilPeponnet** [comment]
Thanks I'll give a try.
